company: UCI Retail Audit Ltd
currency: GBP
territory: All Territories
customer_group: Commercial
item_group: UCI Retail Items
warehouse: Stores - URA
income_account: Sales - URA
receivable_account: Debtors - URA
cost_center: Main - URA
submit_documents: false
chunk_size: 100

